<?php

function dna_generator_menu() {
	$items['dna_generator'] = array(
		'title' => t('DNA Generator'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('dna_generator_form'),
		'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM,
	);
	return $items;
}
// FORM
function dna_generator_form() {
	$form['dna_strand'] = array(
		'#title' => t('Half of a Double Helix'),
		'#description' => t('Please enter a string of the letters "A", "C", "G", or "T" to find the other half.'),
		'#type' => 'textfield',
		'#element_validate' => array('element_validate_input_strand'),
		'#required' => TRUE,
	);
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => 'Complete that Double Helix!',
	);
	return $form;
}
// VALIDATION
function element_validate_input_strand($element) {
	$upper_case_input_strand = strtoupper($element['#value']);
	$split_input_strand = str_split($upper_case_input_strand);

	$nucleotides = array('A', 'C', 'G', 'T');

	foreach($split_input_strand as $letter) {
		if(!in_array($letter, $nucleotides)) {
			form_error($element, t('I told you that it had to be a combination of the letters "A", "C", "G", and "T"!
				<br>
				I\'m not afraid to yell at you again...
				<br>
				I\'m a computer. 
				<br>
				I have no feelings.'));
		}
	}
}
