<?php

function dna_generator_menu() {
	$items['dna_generator'] = array(
		'title' => t('DNA Generator'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('dna_generator_form'),
		'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM,
	);
	return $items;
}
// FORM
function dna_generator_form() {
	$form['dna_strand'] = array(
		'#title' => t('Half of a Double Helix'),
		'#description' => t('Please enter a string of the letters "A", "C", "G", or "T" to find the other half.'),
		'#type' => 'textfield',
		'#required' => TRUE,
	);
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => 'Complete that Double Helix!',
	);
	return $form;
}
