<?php

function dna_generator_menu() {
	$items['dna_generator'] = array(
		'title' => t('DNA Generator'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('dna_generator_form'),
		'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM,
	);
	$items['dna_generator_results_page'] = array(
		'title' => t('DNA Results'),
		'page callback' => 'dna_generator_results',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	return $items;
}
// FORM
function dna_generator_form() {
	$form['dna_strand'] = array(
		'#title' => t('Half of a Double Helix'),
		'#description' => t('Please enter a string of the letters "A", "C", "G", or "T" with no spaces to find the other half.'),
		'#type' => 'textfield',
		'#element_validate' => array('element_validate_input_strand'),
		'#required' => TRUE,
	);
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => 'Complete that Double Helix!',
	);
	return $form;
}
// VALIDATION
function element_validate_input_strand($element) {
	$upper_case_input_strand = strtoupper($element['#value']);
	$split_input_strand = str_split($upper_case_input_strand);

	$nucleotides = array('A', 'C', 'G', 'T');

	foreach($split_input_strand as $letter) {
		if(!in_array($letter, $nucleotides)) {
			form_error($element, t('I told you that it had to be a combination of the letters "A", "C", "G", and "T" with no spaces!
				<br>
				I\'m not afraid to yell at you again...
				<br>
				I\'m a computer. 
				<br>
				I have no feelings.'));
		}
	}
}
// FORM PROCESSING
function create_second_strand_half($first_strand_half) {
	$upper_case_input_strand = strtoupper($first_strand_half);
	$split_input_strand = str_split($upper_case_input_strand);
	$results_array = array();

	foreach($split_input_strand as $letter) {
		if($letter === 'A') {
			array_push($results_array, 'T');
		} elseif($letter === 'T') {
			array_push($results_array, 'A');
		} elseif($letter === 'C') {
			array_push($results_array, 'G');
		} else {
			array_push($results_array, 'C');
		}
	}
	$results = implode('', $results_array);
	return $results;
}
function dna_generator_form_submit($form, &$form_state) {
	$first_strand_half = $form_state['values']['dna_strand'];
	$second_strand_half = create_second_strand_half($first_strand_half);
	
	$_SESSION['original_half'] = strtoupper($first_strand_half);
	$_SESSION['result_half'] = $second_strand_half;
	$form_state['redirect'] = 'dna_generator_results_page';
}
// RESULTS DISPLAY
function dna_generator_results() {
	return '<p>Half 1: ' . $_SESSION['original_half'] . '</p>
			<p>Half 2: ' . $_SESSION['result_half'] . '</p>';
}
